//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JumboSaccoPortal.ProxyReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProxyServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ProxyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MiniStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback DashboardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MemberStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoanGuarantorsReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoanGuaranteedReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoansStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoanRepaymentScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback MemberStatementLoansOperationCompleted;
        
        private System.Threading.SendOrPostCallback MemberLoansOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoanTypesCalculatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback NextOfkinDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback MemberLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmLoginOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback PasswordResetInitiationOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmResetOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNewPaswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetPasswordOnPortalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberOnlineLoanApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoanApplicationDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveGuarantorByRequestorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchGuarantorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGuarantorOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartLoanApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberGuarantorshipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuarantroshipDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartGuarantorshipApprovalOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompleteGuarantorshipApprovalOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectGuarantorshipOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoanUserDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProxyService() {
            this.Url = global::JumboSaccoPortal.Properties.Settings.Default.JumboSaccoPortal_ProxyReference_ProxyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MiniStatementCompletedEventHandler MiniStatementCompleted;
        
        /// <remarks/>
        public event DashboardInfoCompletedEventHandler DashboardInfoCompleted;
        
        /// <remarks/>
        public event MemberStatementCompletedEventHandler MemberStatementCompleted;
        
        /// <remarks/>
        public event LoanGuarantorsReportCompletedEventHandler LoanGuarantorsReportCompleted;
        
        /// <remarks/>
        public event LoanGuaranteedReportCompletedEventHandler LoanGuaranteedReportCompleted;
        
        /// <remarks/>
        public event LoansStatementCompletedEventHandler LoansStatementCompleted;
        
        /// <remarks/>
        public event LoanRepaymentScheduleCompletedEventHandler LoanRepaymentScheduleCompleted;
        
        /// <remarks/>
        public event MemberStatementLoansCompletedEventHandler MemberStatementLoansCompleted;
        
        /// <remarks/>
        public event MemberLoansCompletedEventHandler MemberLoansCompleted;
        
        /// <remarks/>
        public event LoanTypesCalculatorCompletedEventHandler LoanTypesCalculatorCompleted;
        
        /// <remarks/>
        public event NextOfkinDetailsCompletedEventHandler NextOfkinDetailsCompleted;
        
        /// <remarks/>
        public event MemberLoginCompletedEventHandler MemberLoginCompleted;
        
        /// <remarks/>
        public event ConfirmLoginOTPCompletedEventHandler ConfirmLoginOTPCompleted;
        
        /// <remarks/>
        public event PasswordResetInitiationCompletedEventHandler PasswordResetInitiationCompleted;
        
        /// <remarks/>
        public event ConfirmResetOTPCompletedEventHandler ConfirmResetOTPCompleted;
        
        /// <remarks/>
        public event UpdateNewPaswordCompletedEventHandler UpdateNewPaswordCompleted;
        
        /// <remarks/>
        public event ResetPasswordOnPortalCompletedEventHandler ResetPasswordOnPortalCompleted;
        
        /// <remarks/>
        public event GetMemberOnlineLoanApplicationsCompletedEventHandler GetMemberOnlineLoanApplicationsCompleted;
        
        /// <remarks/>
        public event GetLoanApplicationDetailsCompletedEventHandler GetLoanApplicationDetailsCompleted;
        
        /// <remarks/>
        public event RemoveGuarantorByRequestorCompletedEventHandler RemoveGuarantorByRequestorCompleted;
        
        /// <remarks/>
        public event SearchGuarantorCompletedEventHandler SearchGuarantorCompleted;
        
        /// <remarks/>
        public event AddGuarantorCompletedEventHandler AddGuarantorCompleted;
        
        /// <remarks/>
        public event StartLoanApplicationsCompletedEventHandler StartLoanApplicationsCompleted;
        
        /// <remarks/>
        public event GetMemberGuarantorshipsCompletedEventHandler GetMemberGuarantorshipsCompleted;
        
        /// <remarks/>
        public event GuarantroshipDetailsCompletedEventHandler GuarantroshipDetailsCompleted;
        
        /// <remarks/>
        public event StartGuarantorshipApprovalCompletedEventHandler StartGuarantorshipApprovalCompleted;
        
        /// <remarks/>
        public event CompleteGuarantorshipApprovalCompletedEventHandler CompleteGuarantorshipApprovalCompleted;
        
        /// <remarks/>
        public event RejectGuarantorshipCompletedEventHandler RejectGuarantorshipCompleted;
        
        /// <remarks/>
        public event LoanUserDetailsCompletedEventHandler LoanUserDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MiniStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MiniStatement(string membno) {
            object[] results = this.Invoke("MiniStatement", new object[] {
                        membno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MiniStatementAsync(string membno) {
            this.MiniStatementAsync(membno, null);
        }
        
        /// <remarks/>
        public void MiniStatementAsync(string membno, object userState) {
            if ((this.MiniStatementOperationCompleted == null)) {
                this.MiniStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMiniStatementOperationCompleted);
            }
            this.InvokeAsync("MiniStatement", new object[] {
                        membno}, this.MiniStatementOperationCompleted, userState);
        }
        
        private void OnMiniStatementOperationCompleted(object arg) {
            if ((this.MiniStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MiniStatementCompleted(this, new MiniStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DashboardInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DashboardInfo(string membernumber) {
            object[] results = this.Invoke("DashboardInfo", new object[] {
                        membernumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DashboardInfoAsync(string membernumber) {
            this.DashboardInfoAsync(membernumber, null);
        }
        
        /// <remarks/>
        public void DashboardInfoAsync(string membernumber, object userState) {
            if ((this.DashboardInfoOperationCompleted == null)) {
                this.DashboardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDashboardInfoOperationCompleted);
            }
            this.InvokeAsync("DashboardInfo", new object[] {
                        membernumber}, this.DashboardInfoOperationCompleted, userState);
        }
        
        private void OnDashboardInfoOperationCompleted(object arg) {
            if ((this.DashboardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DashboardInfoCompleted(this, new DashboardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MemberStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MemberStatement(string membno, string startdate, string enddate) {
            object[] results = this.Invoke("MemberStatement", new object[] {
                        membno,
                        startdate,
                        enddate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MemberStatementAsync(string membno, string startdate, string enddate) {
            this.MemberStatementAsync(membno, startdate, enddate, null);
        }
        
        /// <remarks/>
        public void MemberStatementAsync(string membno, string startdate, string enddate, object userState) {
            if ((this.MemberStatementOperationCompleted == null)) {
                this.MemberStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMemberStatementOperationCompleted);
            }
            this.InvokeAsync("MemberStatement", new object[] {
                        membno,
                        startdate,
                        enddate}, this.MemberStatementOperationCompleted, userState);
        }
        
        private void OnMemberStatementOperationCompleted(object arg) {
            if ((this.MemberStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MemberStatementCompleted(this, new MemberStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoanGuarantorsReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoanGuarantorsReport(string membno) {
            object[] results = this.Invoke("LoanGuarantorsReport", new object[] {
                        membno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoanGuarantorsReportAsync(string membno) {
            this.LoanGuarantorsReportAsync(membno, null);
        }
        
        /// <remarks/>
        public void LoanGuarantorsReportAsync(string membno, object userState) {
            if ((this.LoanGuarantorsReportOperationCompleted == null)) {
                this.LoanGuarantorsReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoanGuarantorsReportOperationCompleted);
            }
            this.InvokeAsync("LoanGuarantorsReport", new object[] {
                        membno}, this.LoanGuarantorsReportOperationCompleted, userState);
        }
        
        private void OnLoanGuarantorsReportOperationCompleted(object arg) {
            if ((this.LoanGuarantorsReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoanGuarantorsReportCompleted(this, new LoanGuarantorsReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoanGuaranteedReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoanGuaranteedReport(string membno) {
            object[] results = this.Invoke("LoanGuaranteedReport", new object[] {
                        membno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoanGuaranteedReportAsync(string membno) {
            this.LoanGuaranteedReportAsync(membno, null);
        }
        
        /// <remarks/>
        public void LoanGuaranteedReportAsync(string membno, object userState) {
            if ((this.LoanGuaranteedReportOperationCompleted == null)) {
                this.LoanGuaranteedReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoanGuaranteedReportOperationCompleted);
            }
            this.InvokeAsync("LoanGuaranteedReport", new object[] {
                        membno}, this.LoanGuaranteedReportOperationCompleted, userState);
        }
        
        private void OnLoanGuaranteedReportOperationCompleted(object arg) {
            if ((this.LoanGuaranteedReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoanGuaranteedReportCompleted(this, new LoanGuaranteedReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoansStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoansStatement(string membno) {
            object[] results = this.Invoke("LoansStatement", new object[] {
                        membno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoansStatementAsync(string membno) {
            this.LoansStatementAsync(membno, null);
        }
        
        /// <remarks/>
        public void LoansStatementAsync(string membno, object userState) {
            if ((this.LoansStatementOperationCompleted == null)) {
                this.LoansStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoansStatementOperationCompleted);
            }
            this.InvokeAsync("LoansStatement", new object[] {
                        membno}, this.LoansStatementOperationCompleted, userState);
        }
        
        private void OnLoansStatementOperationCompleted(object arg) {
            if ((this.LoansStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoansStatementCompleted(this, new LoansStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoanRepaymentSchedule", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoanRepaymentSchedule(string loannumber) {
            object[] results = this.Invoke("LoanRepaymentSchedule", new object[] {
                        loannumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoanRepaymentScheduleAsync(string loannumber) {
            this.LoanRepaymentScheduleAsync(loannumber, null);
        }
        
        /// <remarks/>
        public void LoanRepaymentScheduleAsync(string loannumber, object userState) {
            if ((this.LoanRepaymentScheduleOperationCompleted == null)) {
                this.LoanRepaymentScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoanRepaymentScheduleOperationCompleted);
            }
            this.InvokeAsync("LoanRepaymentSchedule", new object[] {
                        loannumber}, this.LoanRepaymentScheduleOperationCompleted, userState);
        }
        
        private void OnLoanRepaymentScheduleOperationCompleted(object arg) {
            if ((this.LoanRepaymentScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoanRepaymentScheduleCompleted(this, new LoanRepaymentScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MemberStatementLoans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MemberStatementLoans(string membernumber) {
            object[] results = this.Invoke("MemberStatementLoans", new object[] {
                        membernumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MemberStatementLoansAsync(string membernumber) {
            this.MemberStatementLoansAsync(membernumber, null);
        }
        
        /// <remarks/>
        public void MemberStatementLoansAsync(string membernumber, object userState) {
            if ((this.MemberStatementLoansOperationCompleted == null)) {
                this.MemberStatementLoansOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMemberStatementLoansOperationCompleted);
            }
            this.InvokeAsync("MemberStatementLoans", new object[] {
                        membernumber}, this.MemberStatementLoansOperationCompleted, userState);
        }
        
        private void OnMemberStatementLoansOperationCompleted(object arg) {
            if ((this.MemberStatementLoansCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MemberStatementLoansCompleted(this, new MemberStatementLoansCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MemberLoans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MemberLoans(string membernumber) {
            object[] results = this.Invoke("MemberLoans", new object[] {
                        membernumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MemberLoansAsync(string membernumber) {
            this.MemberLoansAsync(membernumber, null);
        }
        
        /// <remarks/>
        public void MemberLoansAsync(string membernumber, object userState) {
            if ((this.MemberLoansOperationCompleted == null)) {
                this.MemberLoansOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMemberLoansOperationCompleted);
            }
            this.InvokeAsync("MemberLoans", new object[] {
                        membernumber}, this.MemberLoansOperationCompleted, userState);
        }
        
        private void OnMemberLoansOperationCompleted(object arg) {
            if ((this.MemberLoansCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MemberLoansCompleted(this, new MemberLoansCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoanTypesCalculator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoanTypesCalculator(string membernumber) {
            object[] results = this.Invoke("LoanTypesCalculator", new object[] {
                        membernumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoanTypesCalculatorAsync(string membernumber) {
            this.LoanTypesCalculatorAsync(membernumber, null);
        }
        
        /// <remarks/>
        public void LoanTypesCalculatorAsync(string membernumber, object userState) {
            if ((this.LoanTypesCalculatorOperationCompleted == null)) {
                this.LoanTypesCalculatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoanTypesCalculatorOperationCompleted);
            }
            this.InvokeAsync("LoanTypesCalculator", new object[] {
                        membernumber}, this.LoanTypesCalculatorOperationCompleted, userState);
        }
        
        private void OnLoanTypesCalculatorOperationCompleted(object arg) {
            if ((this.LoanTypesCalculatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoanTypesCalculatorCompleted(this, new LoanTypesCalculatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NextOfkinDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NextOfkinDetails(string membernumber) {
            object[] results = this.Invoke("NextOfkinDetails", new object[] {
                        membernumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NextOfkinDetailsAsync(string membernumber) {
            this.NextOfkinDetailsAsync(membernumber, null);
        }
        
        /// <remarks/>
        public void NextOfkinDetailsAsync(string membernumber, object userState) {
            if ((this.NextOfkinDetailsOperationCompleted == null)) {
                this.NextOfkinDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNextOfkinDetailsOperationCompleted);
            }
            this.InvokeAsync("NextOfkinDetails", new object[] {
                        membernumber}, this.NextOfkinDetailsOperationCompleted, userState);
        }
        
        private void OnNextOfkinDetailsOperationCompleted(object arg) {
            if ((this.NextOfkinDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NextOfkinDetailsCompleted(this, new NextOfkinDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MemberLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MemberLogin(string username, string password) {
            object[] results = this.Invoke("MemberLogin", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MemberLoginAsync(string username, string password) {
            this.MemberLoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void MemberLoginAsync(string username, string password, object userState) {
            if ((this.MemberLoginOperationCompleted == null)) {
                this.MemberLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMemberLoginOperationCompleted);
            }
            this.InvokeAsync("MemberLogin", new object[] {
                        username,
                        password}, this.MemberLoginOperationCompleted, userState);
        }
        
        private void OnMemberLoginOperationCompleted(object arg) {
            if ((this.MemberLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MemberLoginCompleted(this, new MemberLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmLoginOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmLoginOTP(string username, string otp) {
            object[] results = this.Invoke("ConfirmLoginOTP", new object[] {
                        username,
                        otp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmLoginOTPAsync(string username, string otp) {
            this.ConfirmLoginOTPAsync(username, otp, null);
        }
        
        /// <remarks/>
        public void ConfirmLoginOTPAsync(string username, string otp, object userState) {
            if ((this.ConfirmLoginOTPOperationCompleted == null)) {
                this.ConfirmLoginOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmLoginOTPOperationCompleted);
            }
            this.InvokeAsync("ConfirmLoginOTP", new object[] {
                        username,
                        otp}, this.ConfirmLoginOTPOperationCompleted, userState);
        }
        
        private void OnConfirmLoginOTPOperationCompleted(object arg) {
            if ((this.ConfirmLoginOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmLoginOTPCompleted(this, new ConfirmLoginOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PasswordResetInitiation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PasswordResetInitiation(string username) {
            object[] results = this.Invoke("PasswordResetInitiation", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PasswordResetInitiationAsync(string username) {
            this.PasswordResetInitiationAsync(username, null);
        }
        
        /// <remarks/>
        public void PasswordResetInitiationAsync(string username, object userState) {
            if ((this.PasswordResetInitiationOperationCompleted == null)) {
                this.PasswordResetInitiationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPasswordResetInitiationOperationCompleted);
            }
            this.InvokeAsync("PasswordResetInitiation", new object[] {
                        username}, this.PasswordResetInitiationOperationCompleted, userState);
        }
        
        private void OnPasswordResetInitiationOperationCompleted(object arg) {
            if ((this.PasswordResetInitiationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PasswordResetInitiationCompleted(this, new PasswordResetInitiationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmResetOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmResetOTP(string username, string otp) {
            object[] results = this.Invoke("ConfirmResetOTP", new object[] {
                        username,
                        otp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmResetOTPAsync(string username, string otp) {
            this.ConfirmResetOTPAsync(username, otp, null);
        }
        
        /// <remarks/>
        public void ConfirmResetOTPAsync(string username, string otp, object userState) {
            if ((this.ConfirmResetOTPOperationCompleted == null)) {
                this.ConfirmResetOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmResetOTPOperationCompleted);
            }
            this.InvokeAsync("ConfirmResetOTP", new object[] {
                        username,
                        otp}, this.ConfirmResetOTPOperationCompleted, userState);
        }
        
        private void OnConfirmResetOTPOperationCompleted(object arg) {
            if ((this.ConfirmResetOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmResetOTPCompleted(this, new ConfirmResetOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateNewPasword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateNewPasword(string username, string password) {
            object[] results = this.Invoke("UpdateNewPasword", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateNewPaswordAsync(string username, string password) {
            this.UpdateNewPaswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void UpdateNewPaswordAsync(string username, string password, object userState) {
            if ((this.UpdateNewPaswordOperationCompleted == null)) {
                this.UpdateNewPaswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNewPaswordOperationCompleted);
            }
            this.InvokeAsync("UpdateNewPasword", new object[] {
                        username,
                        password}, this.UpdateNewPaswordOperationCompleted, userState);
        }
        
        private void OnUpdateNewPaswordOperationCompleted(object arg) {
            if ((this.UpdateNewPaswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNewPaswordCompleted(this, new UpdateNewPaswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetPasswordOnPortal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ResetPasswordOnPortal(string username, string oldpassword, string newpassword) {
            object[] results = this.Invoke("ResetPasswordOnPortal", new object[] {
                        username,
                        oldpassword,
                        newpassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ResetPasswordOnPortalAsync(string username, string oldpassword, string newpassword) {
            this.ResetPasswordOnPortalAsync(username, oldpassword, newpassword, null);
        }
        
        /// <remarks/>
        public void ResetPasswordOnPortalAsync(string username, string oldpassword, string newpassword, object userState) {
            if ((this.ResetPasswordOnPortalOperationCompleted == null)) {
                this.ResetPasswordOnPortalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetPasswordOnPortalOperationCompleted);
            }
            this.InvokeAsync("ResetPasswordOnPortal", new object[] {
                        username,
                        oldpassword,
                        newpassword}, this.ResetPasswordOnPortalOperationCompleted, userState);
        }
        
        private void OnResetPasswordOnPortalOperationCompleted(object arg) {
            if ((this.ResetPasswordOnPortalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetPasswordOnPortalCompleted(this, new ResetPasswordOnPortalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberOnlineLoanApplications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMemberOnlineLoanApplications(string memberid) {
            object[] results = this.Invoke("GetMemberOnlineLoanApplications", new object[] {
                        memberid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberOnlineLoanApplicationsAsync(string memberid) {
            this.GetMemberOnlineLoanApplicationsAsync(memberid, null);
        }
        
        /// <remarks/>
        public void GetMemberOnlineLoanApplicationsAsync(string memberid, object userState) {
            if ((this.GetMemberOnlineLoanApplicationsOperationCompleted == null)) {
                this.GetMemberOnlineLoanApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberOnlineLoanApplicationsOperationCompleted);
            }
            this.InvokeAsync("GetMemberOnlineLoanApplications", new object[] {
                        memberid}, this.GetMemberOnlineLoanApplicationsOperationCompleted, userState);
        }
        
        private void OnGetMemberOnlineLoanApplicationsOperationCompleted(object arg) {
            if ((this.GetMemberOnlineLoanApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberOnlineLoanApplicationsCompleted(this, new GetMemberOnlineLoanApplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoanApplicationDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLoanApplicationDetails(int loanid) {
            object[] results = this.Invoke("GetLoanApplicationDetails", new object[] {
                        loanid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanApplicationDetailsAsync(int loanid) {
            this.GetLoanApplicationDetailsAsync(loanid, null);
        }
        
        /// <remarks/>
        public void GetLoanApplicationDetailsAsync(int loanid, object userState) {
            if ((this.GetLoanApplicationDetailsOperationCompleted == null)) {
                this.GetLoanApplicationDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanApplicationDetailsOperationCompleted);
            }
            this.InvokeAsync("GetLoanApplicationDetails", new object[] {
                        loanid}, this.GetLoanApplicationDetailsOperationCompleted, userState);
        }
        
        private void OnGetLoanApplicationDetailsOperationCompleted(object arg) {
            if ((this.GetLoanApplicationDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanApplicationDetailsCompleted(this, new GetLoanApplicationDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveGuarantorByRequestor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemoveGuarantorByRequestor(int guarantorshipid) {
            object[] results = this.Invoke("RemoveGuarantorByRequestor", new object[] {
                        guarantorshipid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveGuarantorByRequestorAsync(int guarantorshipid) {
            this.RemoveGuarantorByRequestorAsync(guarantorshipid, null);
        }
        
        /// <remarks/>
        public void RemoveGuarantorByRequestorAsync(int guarantorshipid, object userState) {
            if ((this.RemoveGuarantorByRequestorOperationCompleted == null)) {
                this.RemoveGuarantorByRequestorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveGuarantorByRequestorOperationCompleted);
            }
            this.InvokeAsync("RemoveGuarantorByRequestor", new object[] {
                        guarantorshipid}, this.RemoveGuarantorByRequestorOperationCompleted, userState);
        }
        
        private void OnRemoveGuarantorByRequestorOperationCompleted(object arg) {
            if ((this.RemoveGuarantorByRequestorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveGuarantorByRequestorCompleted(this, new RemoveGuarantorByRequestorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchGuarantor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchGuarantor(string guarantorid) {
            object[] results = this.Invoke("SearchGuarantor", new object[] {
                        guarantorid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchGuarantorAsync(string guarantorid) {
            this.SearchGuarantorAsync(guarantorid, null);
        }
        
        /// <remarks/>
        public void SearchGuarantorAsync(string guarantorid, object userState) {
            if ((this.SearchGuarantorOperationCompleted == null)) {
                this.SearchGuarantorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchGuarantorOperationCompleted);
            }
            this.InvokeAsync("SearchGuarantor", new object[] {
                        guarantorid}, this.SearchGuarantorOperationCompleted, userState);
        }
        
        private void OnSearchGuarantorOperationCompleted(object arg) {
            if ((this.SearchGuarantorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchGuarantorCompleted(this, new SearchGuarantorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddGuarantor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddGuarantor(int loanid, string guarantorid) {
            object[] results = this.Invoke("AddGuarantor", new object[] {
                        loanid,
                        guarantorid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddGuarantorAsync(int loanid, string guarantorid) {
            this.AddGuarantorAsync(loanid, guarantorid, null);
        }
        
        /// <remarks/>
        public void AddGuarantorAsync(int loanid, string guarantorid, object userState) {
            if ((this.AddGuarantorOperationCompleted == null)) {
                this.AddGuarantorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGuarantorOperationCompleted);
            }
            this.InvokeAsync("AddGuarantor", new object[] {
                        loanid,
                        guarantorid}, this.AddGuarantorOperationCompleted, userState);
        }
        
        private void OnAddGuarantorOperationCompleted(object arg) {
            if ((this.AddGuarantorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGuarantorCompleted(this, new AddGuarantorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartLoanApplications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StartLoanApplications(string memberid, string loantype, decimal requestedamount, string foldername) {
            object[] results = this.Invoke("StartLoanApplications", new object[] {
                        memberid,
                        loantype,
                        requestedamount,
                        foldername});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StartLoanApplicationsAsync(string memberid, string loantype, decimal requestedamount, string foldername) {
            this.StartLoanApplicationsAsync(memberid, loantype, requestedamount, foldername, null);
        }
        
        /// <remarks/>
        public void StartLoanApplicationsAsync(string memberid, string loantype, decimal requestedamount, string foldername, object userState) {
            if ((this.StartLoanApplicationsOperationCompleted == null)) {
                this.StartLoanApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartLoanApplicationsOperationCompleted);
            }
            this.InvokeAsync("StartLoanApplications", new object[] {
                        memberid,
                        loantype,
                        requestedamount,
                        foldername}, this.StartLoanApplicationsOperationCompleted, userState);
        }
        
        private void OnStartLoanApplicationsOperationCompleted(object arg) {
            if ((this.StartLoanApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartLoanApplicationsCompleted(this, new StartLoanApplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberGuarantorships", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMemberGuarantorships(string memberid) {
            object[] results = this.Invoke("GetMemberGuarantorships", new object[] {
                        memberid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberGuarantorshipsAsync(string memberid) {
            this.GetMemberGuarantorshipsAsync(memberid, null);
        }
        
        /// <remarks/>
        public void GetMemberGuarantorshipsAsync(string memberid, object userState) {
            if ((this.GetMemberGuarantorshipsOperationCompleted == null)) {
                this.GetMemberGuarantorshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberGuarantorshipsOperationCompleted);
            }
            this.InvokeAsync("GetMemberGuarantorships", new object[] {
                        memberid}, this.GetMemberGuarantorshipsOperationCompleted, userState);
        }
        
        private void OnGetMemberGuarantorshipsOperationCompleted(object arg) {
            if ((this.GetMemberGuarantorshipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberGuarantorshipsCompleted(this, new GetMemberGuarantorshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuarantroshipDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuarantroshipDetails(int guarantorship) {
            object[] results = this.Invoke("GuarantroshipDetails", new object[] {
                        guarantorship});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuarantroshipDetailsAsync(int guarantorship) {
            this.GuarantroshipDetailsAsync(guarantorship, null);
        }
        
        /// <remarks/>
        public void GuarantroshipDetailsAsync(int guarantorship, object userState) {
            if ((this.GuarantroshipDetailsOperationCompleted == null)) {
                this.GuarantroshipDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuarantroshipDetailsOperationCompleted);
            }
            this.InvokeAsync("GuarantroshipDetails", new object[] {
                        guarantorship}, this.GuarantroshipDetailsOperationCompleted, userState);
        }
        
        private void OnGuarantroshipDetailsOperationCompleted(object arg) {
            if ((this.GuarantroshipDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuarantroshipDetailsCompleted(this, new GuarantroshipDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartGuarantorshipApproval", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StartGuarantorshipApproval(int guarantorship, string memberid, decimal amount) {
            object[] results = this.Invoke("StartGuarantorshipApproval", new object[] {
                        guarantorship,
                        memberid,
                        amount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StartGuarantorshipApprovalAsync(int guarantorship, string memberid, decimal amount) {
            this.StartGuarantorshipApprovalAsync(guarantorship, memberid, amount, null);
        }
        
        /// <remarks/>
        public void StartGuarantorshipApprovalAsync(int guarantorship, string memberid, decimal amount, object userState) {
            if ((this.StartGuarantorshipApprovalOperationCompleted == null)) {
                this.StartGuarantorshipApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartGuarantorshipApprovalOperationCompleted);
            }
            this.InvokeAsync("StartGuarantorshipApproval", new object[] {
                        guarantorship,
                        memberid,
                        amount}, this.StartGuarantorshipApprovalOperationCompleted, userState);
        }
        
        private void OnStartGuarantorshipApprovalOperationCompleted(object arg) {
            if ((this.StartGuarantorshipApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartGuarantorshipApprovalCompleted(this, new StartGuarantorshipApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CompleteGuarantorshipApproval", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompleteGuarantorshipApproval(int guarantorship, string memberid, string otp) {
            object[] results = this.Invoke("CompleteGuarantorshipApproval", new object[] {
                        guarantorship,
                        memberid,
                        otp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CompleteGuarantorshipApprovalAsync(int guarantorship, string memberid, string otp) {
            this.CompleteGuarantorshipApprovalAsync(guarantorship, memberid, otp, null);
        }
        
        /// <remarks/>
        public void CompleteGuarantorshipApprovalAsync(int guarantorship, string memberid, string otp, object userState) {
            if ((this.CompleteGuarantorshipApprovalOperationCompleted == null)) {
                this.CompleteGuarantorshipApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompleteGuarantorshipApprovalOperationCompleted);
            }
            this.InvokeAsync("CompleteGuarantorshipApproval", new object[] {
                        guarantorship,
                        memberid,
                        otp}, this.CompleteGuarantorshipApprovalOperationCompleted, userState);
        }
        
        private void OnCompleteGuarantorshipApprovalOperationCompleted(object arg) {
            if ((this.CompleteGuarantorshipApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompleteGuarantorshipApprovalCompleted(this, new CompleteGuarantorshipApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RejectGuarantorship", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RejectGuarantorship(int guarantorship, string memberid, string comment) {
            object[] results = this.Invoke("RejectGuarantorship", new object[] {
                        guarantorship,
                        memberid,
                        comment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RejectGuarantorshipAsync(int guarantorship, string memberid, string comment) {
            this.RejectGuarantorshipAsync(guarantorship, memberid, comment, null);
        }
        
        /// <remarks/>
        public void RejectGuarantorshipAsync(int guarantorship, string memberid, string comment, object userState) {
            if ((this.RejectGuarantorshipOperationCompleted == null)) {
                this.RejectGuarantorshipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectGuarantorshipOperationCompleted);
            }
            this.InvokeAsync("RejectGuarantorship", new object[] {
                        guarantorship,
                        memberid,
                        comment}, this.RejectGuarantorshipOperationCompleted, userState);
        }
        
        private void OnRejectGuarantorshipOperationCompleted(object arg) {
            if ((this.RejectGuarantorshipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectGuarantorshipCompleted(this, new RejectGuarantorshipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoanUserDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoanUserDetails(string memberid) {
            object[] results = this.Invoke("LoanUserDetails", new object[] {
                        memberid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoanUserDetailsAsync(string memberid) {
            this.LoanUserDetailsAsync(memberid, null);
        }
        
        /// <remarks/>
        public void LoanUserDetailsAsync(string memberid, object userState) {
            if ((this.LoanUserDetailsOperationCompleted == null)) {
                this.LoanUserDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoanUserDetailsOperationCompleted);
            }
            this.InvokeAsync("LoanUserDetails", new object[] {
                        memberid}, this.LoanUserDetailsOperationCompleted, userState);
        }
        
        private void OnLoanUserDetailsOperationCompleted(object arg) {
            if ((this.LoanUserDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoanUserDetailsCompleted(this, new LoanUserDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MiniStatementCompletedEventHandler(object sender, MiniStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MiniStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MiniStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DashboardInfoCompletedEventHandler(object sender, DashboardInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DashboardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DashboardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MemberStatementCompletedEventHandler(object sender, MemberStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MemberStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MemberStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoanGuarantorsReportCompletedEventHandler(object sender, LoanGuarantorsReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanGuarantorsReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoanGuarantorsReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoanGuaranteedReportCompletedEventHandler(object sender, LoanGuaranteedReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanGuaranteedReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoanGuaranteedReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoansStatementCompletedEventHandler(object sender, LoansStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoansStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoansStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoanRepaymentScheduleCompletedEventHandler(object sender, LoanRepaymentScheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanRepaymentScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoanRepaymentScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MemberStatementLoansCompletedEventHandler(object sender, MemberStatementLoansCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MemberStatementLoansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MemberStatementLoansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MemberLoansCompletedEventHandler(object sender, MemberLoansCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MemberLoansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MemberLoansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoanTypesCalculatorCompletedEventHandler(object sender, LoanTypesCalculatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanTypesCalculatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoanTypesCalculatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void NextOfkinDetailsCompletedEventHandler(object sender, NextOfkinDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NextOfkinDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NextOfkinDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MemberLoginCompletedEventHandler(object sender, MemberLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MemberLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MemberLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ConfirmLoginOTPCompletedEventHandler(object sender, ConfirmLoginOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmLoginOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmLoginOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PasswordResetInitiationCompletedEventHandler(object sender, PasswordResetInitiationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PasswordResetInitiationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PasswordResetInitiationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ConfirmResetOTPCompletedEventHandler(object sender, ConfirmResetOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmResetOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmResetOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateNewPaswordCompletedEventHandler(object sender, UpdateNewPaswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateNewPaswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateNewPaswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ResetPasswordOnPortalCompletedEventHandler(object sender, ResetPasswordOnPortalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetPasswordOnPortalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetPasswordOnPortalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetMemberOnlineLoanApplicationsCompletedEventHandler(object sender, GetMemberOnlineLoanApplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberOnlineLoanApplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberOnlineLoanApplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetLoanApplicationDetailsCompletedEventHandler(object sender, GetLoanApplicationDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanApplicationDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanApplicationDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RemoveGuarantorByRequestorCompletedEventHandler(object sender, RemoveGuarantorByRequestorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveGuarantorByRequestorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveGuarantorByRequestorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SearchGuarantorCompletedEventHandler(object sender, SearchGuarantorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchGuarantorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchGuarantorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddGuarantorCompletedEventHandler(object sender, AddGuarantorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddGuarantorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGuarantorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void StartLoanApplicationsCompletedEventHandler(object sender, StartLoanApplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartLoanApplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartLoanApplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetMemberGuarantorshipsCompletedEventHandler(object sender, GetMemberGuarantorshipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberGuarantorshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberGuarantorshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GuarantroshipDetailsCompletedEventHandler(object sender, GuarantroshipDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuarantroshipDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuarantroshipDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void StartGuarantorshipApprovalCompletedEventHandler(object sender, StartGuarantorshipApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartGuarantorshipApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartGuarantorshipApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CompleteGuarantorshipApprovalCompletedEventHandler(object sender, CompleteGuarantorshipApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompleteGuarantorshipApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompleteGuarantorshipApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RejectGuarantorshipCompletedEventHandler(object sender, RejectGuarantorshipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectGuarantorshipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectGuarantorshipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoanUserDetailsCompletedEventHandler(object sender, LoanUserDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanUserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoanUserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591